version: "3.4"

services:
  backend:
    build:
      context: ../
      dockerfile: ./.docker/images/backend/Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - redis

  redis:
    image: redis:6.0
